{% set name = "napari-indices" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-indices-{{ version }}.tar.gz
  sha256: 6bec2a6389b97036318b1a43803e552081913f3062f29453ae518370dde0d557
  patches:
    - qtpy.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - magicgui
    - matplotlib
    - napari
    - numpy
    - python >={{ python_min }}
    - qtpy
    - spectral
    - tifffile

test:
  imports:
    - napari_indices
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-indices
  summary: Calculer les indices de végétation
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
